# Generated by Django 5.1.3 on 2025-03-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delocation_delete_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='delocation',
            name='description',
            field=models.TextField(default='', max_length=1000000000000000000000000),
        ),
    ]
